### ISSUE TITLE
Problem creating the connection

### ISSUE THREAD

**Issue by amfgomez** [rwynn/mongofluxd#3]
Hello 

I have been having problems to execute the mongofluxd.

My case is the following:
Database name: cygnus_malaga
Collections name: cygnus_/espaciosmedioambientales_sensor2_multisensor
The document:
{ "_id" : ObjectId("5bb3a13a189096000aa5d332"), "recvTime" : ISODate("2018-10-02T16:47:44.041Z"), "humidity" : "80.3", "temperature" : "25.22", "timestamp" : "1539854746" }

The config file is the following:

influx-url = "http://influxdb:8086"
influx-skip-verify = true
influx-auto-create-db = true
influx-clients = 10
mongo-url = "mongo:27020"
mongo-skip-verify = true
replay = false
resume = false
resume-name = "mongofluxd"
verbose = false
change-streams = true
direct-reads = true
exit-after-direct-reads = true

[[measurement]]
namespace = "cygnus_malaga."
fields = ["temperature", "float"]
timefield = "timestamp"
precision = "ms"

[[measurement]]
namespace = "cygnus_malaga.['cygnus_/espaciosmedioambientales_sensor2_multisensor']"
fields = ["temperature", "humidity"]
retention = "RP1"
measure = "cygnus_/espaciosmedioambientales_sensor2_multisensor"

Could you help me? please.

**Comment by rwynn** [comment]
You will need MongoDB 3.6+ to use change streams.  Verify that first.  Do you really have such a collection name with a slash?  Since that may cause problems as a measurement name in InfluxDB I would suggest to configure the `measure` property to be more simple.

Try using the following config:

```
influx-url = "http://influxdb:8086"
influx-skip-verify = true
influx-auto-create-db = true
influx-clients = 10
mongo-url = "mongo:27020"
mongo-skip-verify = true
replay = false
resume = false
resume-name = "mongofluxd"
verbose = true
change-streams = true
direct-reads = true
exit-after-direct-reads = true

[[measurement]]
namespace = 'cygnus_malaga.cygnus_/espaciosmedioambientales_sensor2_multisensor'
fields = ["temperature", "humidity"]
timefield = "recvTime"
precision = "ms"
measure = "espaciosmedioambientales_sensor2_multisensor"
```

The `namespace` should always be simply the mongodb database name followed by a dot followed by the mongodb collection name.

Make sure your connection URLs are correct, MongoDB is setup as a replica set, and the data is in the expected database and collection...  

```
rs1:PRIMARY> use cygnus_malaga;
switched to db cygnus_malaga
rs1:PRIMARY> db['cygnus_/espaciosmedioambientales_sensor2_multisensor'].find()
{ "_id" : ObjectId("5bb3a13a189096000aa5d332"), "recvTime" : ISODate("2018-10-02T16:47:44.041Z"), "humidity" : "80.3", "temperature" : "25.22", "timestamp" : "1539854746" }
```

When I run this locally I get the following:

```
$ ./mongofluxd -f ~/influx.toml 
INFO 2018/10/18 16:35:56 no plugins detected
INFO 2018/10/18 16:35:57 1 points flushed
```

And see data in InfluxDB...

```
$ influx
Connected to http://localhost:8086 version 1.4.3
InfluxDB shell version: 1.4.3
> use cygnus_malaga;
Using database cygnus_malaga
> select * from espaciosmedioambientales_sensor2_multisensor;
name: espaciosmedioambientales_sensor2_multisensor
time                humidity temperature
----                -------- -----------
1538498864041000000 80.3     25.22
```

If you get it working you may want to consider then turning `verbose` to false and `exit-after...` to false if you want to continue tailing MongoDB for new events.

If you get errors with the above please report the error message.

**Comment by rwynn** [comment]
Also, if you want to use the retention policy feature on the measurement you will need to create the retention policy before running mongofluxd.

https://docs.influxdata.com/influxdb/v1.6/query_language/database_management/#create-retention-policies-with-create-retention-policy

**Comment by amfgomez** [comment]
Thanks in advance for your help and for your quick reply.
I will check and I will write if the solution works!

Best regard.

**Comment by rwynn** [comment]
@amfgomez do you still need any help?
